### ISSUE TITLE
Найти id для позиций на моем складе

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/masterok#14]
### Задача

Для каждой позиции из [этого файла](https://github.com/torin-asakura/masterok/files/8058915/report-Stock-admin%40olga03081979-2022-02-07-14-34-46.xls) найти id на моем складе

### Алгоритм

На моем складе нужно перейти в раздел Товары -> Товары и услуги

1. Скопировать наименование позиции
2. Вставить в поиск на моем складе

![image](https://user-images.githubusercontent.com/62806448/153824432-536df4fe-2bc2-4fc9-a624-69adfd0d4ddb.png)

3. Перейти в найденную позицию

![image](https://user-images.githubusercontent.com/62806448/153824619-2d8d4dd4-d7f1-4366-bc89-ba82a5e56c60.png)

4. Скопировать id из адресной строки

![image](https://user-images.githubusercontent.com/62806448/153825876-6a810eb2-be21-4e9c-881d-955a78f6fb6b.png)

### В каком формате хранить данные

Для хранения id для каждой позиции можно использовать наиболее удобный для вас формат из предложенных:

1. В `.txt` файле хранить все значения в формате `<наименование позиции> - <id>`, разделяя значения новой строкой

**Пример:**

```javascript
Лампочка FR300 - 7f3a96c8-62f4-11ea-0a80-001b002bc380
Батарейка Energizer - 7f3a96c8-62f4-11ea-0a80-001b002bc380
...
```

При этом разделителем должна быть **тире с пробелами по бокам** (` - `,  вместо `-`)

2. `.json`, где ключ - наименование, значение - id

**Пример:**

```javascript
{
   "Лампочка FR300": "7f3a96c8-62f4-11ea-0a80-001b002bc380",
   "Батарейка Energizer": "7f3a96c8-62f4-11ea-0a80-001b002bc380"
}
```

**Comment by gochicus** [comment]
[item-id.txt](https://github.com/torin-asakura/masterok/files/8059774/item-id.txt)

**Comment by ikorol3107** [comment]
[balance.txt](https://github.com/torin-asakura/masterok/files/8060019/balance.txt)
